// A reference list of grape varieties, each with the regional/historical
// synonyms it's also sold under - e.g. the same grape is "Grenache" in
// France, "Garnacha" in Spain, and "Cannonau" in Sardinia. Backs the
// canonical-variety matching in lib/varietal-match.js, so "show me all my
// Grenache" also finds a bottle logged as Garnacha (BACKLOG.md #1), and
// the autocomplete on the bottle form.
//
// Deliberately a plain static list, not a live third-party API - a personal
// cellar only ever touches a few hundred distinct grapes at most, and a
// fixed list of the ~200 most-planted/most-known varieties covers the
// overwhelming majority of real bottles. Add an entry here (and its known
// synonyms) as an unrecognized one comes up; this is meant to grow, not be
// exhaustive on day one.
//
// Each entry's `aliases` includes the canonical name itself, so matching
// code can treat the array uniformly rather than special-casing it.
export const VARIETALS = [
  // --- Reds with well-known regional synonyms ---
  { canonical: "Grenache", aliases: ["Grenache", "Garnacha", "Garnacha Tinta", "Cannonau"] },
  { canonical: "Mourvèdre", aliases: ["Mourvèdre", "Mourvedre", "Mataro", "Monastrell"] },
  { canonical: "Pinot Noir", aliases: ["Pinot Noir", "Pinot Nero", "Spätburgunder", "Spatburgunder", "Blauburgunder"] },
  { canonical: "Syrah", aliases: ["Syrah", "Shiraz"] },
  { canonical: "Zinfandel", aliases: ["Zinfandel", "Primitivo", "Crljenak Kaštelanski", "Tribidrag"] },
  { canonical: "Carignan", aliases: ["Carignan", "Cariñena", "Carinena", "Carignano", "Mazuelo", "Mazuela"] },
  { canonical: "Tempranillo", aliases: ["Tempranillo", "Tinta Roriz", "Tinto Fino", "Tinto del País", "Tinto del Pais", "Cencibel", "Ull de Llebre", "Aragonez"] },
  { canonical: "Malbec", aliases: ["Malbec", "Cot", "Côt", "Auxerrois"] },
  { canonical: "Cabernet Franc", aliases: ["Cabernet Franc", "Bouchet", "Breton"] },
  { canonical: "Blaufränkisch", aliases: ["Blaufränkisch", "Blaufrankisch", "Kékfrankos", "Kekfrankos", "Lemberger"] },
  { canonical: "Trollinger", aliases: ["Trollinger", "Schiava", "Vernatsch"] },
  { canonical: "Charbono", aliases: ["Charbono", "Bonarda", "Douce Noir", "Corbeau"] },
  { canonical: "País", aliases: ["País", "Pais", "Mission", "Listán Prieto", "Listan Prieto"] },
  { canonical: "Sangiovese", aliases: ["Sangiovese", "Brunello", "Morellino", "Prugnolo Gentile", "Nielluccio"] },
  { canonical: "Nebbiolo", aliases: ["Nebbiolo", "Spanna", "Chiavennasca"] },
  { canonical: "Montepulciano", aliases: ["Montepulciano"] },
  { canonical: "Nero d'Avola", aliases: ["Nero d'Avola", "Nero d Avola", "Calabrese"] },

  // --- Whites with well-known regional synonyms ---
  { canonical: "Sauvignon Blanc", aliases: ["Sauvignon Blanc", "Fumé Blanc", "Fume Blanc"] },
  { canonical: "Pinot Gris", aliases: ["Pinot Gris", "Pinot Grigio", "Grauburgunder", "Ruländer", "Rulander"] },
  { canonical: "Pinot Blanc", aliases: ["Pinot Blanc", "Pinot Bianco", "Weissburgunder", "Klevner"] },
  { canonical: "Chenin Blanc", aliases: ["Chenin Blanc", "Steen"] },
  { canonical: "Grenache Blanc", aliases: ["Grenache Blanc", "Garnacha Blanca"] },
  { canonical: "Riesling", aliases: ["Riesling", "Rhine Riesling", "Johannisberg Riesling", "White Riesling"] },
  { canonical: "Trebbiano", aliases: ["Trebbiano", "Ugni Blanc"] },
  { canonical: "Vermentino", aliases: ["Vermentino", "Rolle", "Pigato"] },
  { canonical: "Viura", aliases: ["Viura", "Macabeo", "Macabeu"] },
  { canonical: "Chasselas", aliases: ["Chasselas", "Fendant", "Gutedel"] },
  { canonical: "Malvasia", aliases: ["Malvasia", "Malvasía", "Malmsey"] },
  { canonical: "Albariño", aliases: ["Albariño", "Albarino", "Alvarinho"] },
  { canonical: "Muscat Blanc à Petits Grains", aliases: ["Muscat Blanc à Petits Grains", "Muscat Blanc a Petits Grains", "Moscato Bianco", "Muscat Canelli", "Moscato"] },

  // --- Other well-known reds (single-name, no widely-used synonym) ---
  { canonical: "Cabernet Sauvignon", aliases: ["Cabernet Sauvignon"] },
  { canonical: "Merlot", aliases: ["Merlot"] },
  { canonical: "Barbera", aliases: ["Barbera"] },
  { canonical: "Dolcetto", aliases: ["Dolcetto"] },
  { canonical: "Gamay", aliases: ["Gamay"] },
  { canonical: "Petit Verdot", aliases: ["Petit Verdot"] },
  { canonical: "Petite Sirah", aliases: ["Petite Sirah", "Durif"] },
  { canonical: "Carmenère", aliases: ["Carmenère", "Carmenere"] },
  { canonical: "Touriga Nacional", aliases: ["Touriga Nacional"] },
  { canonical: "Touriga Franca", aliases: ["Touriga Franca"] },
  { canonical: "Tinta Barroca", aliases: ["Tinta Barroca"] },
  { canonical: "Tinta Cão", aliases: ["Tinta Cão", "Tinta Cao"] },
  { canonical: "Aglianico", aliases: ["Aglianico"] },
  { canonical: "Negroamaro", aliases: ["Negroamaro"] },
  { canonical: "Cinsault", aliases: ["Cinsault", "Cinsaut"] },
  { canonical: "Pinotage", aliases: ["Pinotage"] },
  { canonical: "Corvina", aliases: ["Corvina"] },
  { canonical: "Rondinella", aliases: ["Rondinella"] },
  { canonical: "Molinara", aliases: ["Molinara"] },
  { canonical: "Xinomavro", aliases: ["Xinomavro"] },
  { canonical: "Agiorgitiko", aliases: ["Agiorgitiko"] },
  { canonical: "Saperavi", aliases: ["Saperavi"] },
  { canonical: "Zweigelt", aliases: ["Zweigelt"] },
  { canonical: "St. Laurent", aliases: ["St. Laurent", "Sankt Laurent", "St Laurent"] },
  { canonical: "Dornfelder", aliases: ["Dornfelder"] },
  { canonical: "Lagrein", aliases: ["Lagrein"] },
  { canonical: "Teroldego", aliases: ["Teroldego"] },
  { canonical: "Nerello Mascalese", aliases: ["Nerello Mascalese"] },
  { canonical: "Frappato", aliases: ["Frappato"] },
  { canonical: "Baga", aliases: ["Baga"] },
  { canonical: "Alicante Bouschet", aliases: ["Alicante Bouschet"] },
  { canonical: "Mencía", aliases: ["Mencía", "Mencia"] },
  { canonical: "Bobal", aliases: ["Bobal"] },
  { canonical: "Graciano", aliases: ["Graciano"] },
  { canonical: "Tannat", aliases: ["Tannat"] },
  { canonical: "Counoise", aliases: ["Counoise"] },
  { canonical: "Lambrusco", aliases: ["Lambrusco"] },
  { canonical: "Freisa", aliases: ["Freisa"] },
  { canonical: "Grignolino", aliases: ["Grignolino"] },
  { canonical: "Kadarka", aliases: ["Kadarka"] },
  { canonical: "Kékoportó", aliases: ["Kékoportó", "Kekoporto", "Blauer Portugieser", "Blue Portuguese"] },
  { canonical: "Pinot Meunier", aliases: ["Pinot Meunier", "Meunier"] },
  { canonical: "Aragonez", aliases: ["Aragonez"] },
  { canonical: "Castelão", aliases: ["Castelão", "Castelao", "Periquita"] },

  // --- Other well-known whites (single-name, no widely-used synonym) ---
  { canonical: "Chardonnay", aliases: ["Chardonnay"] },
  { canonical: "Viognier", aliases: ["Viognier"] },
  { canonical: "Sémillon", aliases: ["Sémillon", "Semillon"] },
  { canonical: "Gewürztraminer", aliases: ["Gewürztraminer", "Gewurztraminer", "Traminer"] },
  { canonical: "Grüner Veltliner", aliases: ["Grüner Veltliner", "Gruner Veltliner"] },
  { canonical: "Torrontés", aliases: ["Torrontés", "Torrontes"] },
  { canonical: "Verdejo", aliases: ["Verdejo"] },
  { canonical: "Falanghina", aliases: ["Falanghina"] },
  { canonical: "Fiano", aliases: ["Fiano"] },
  { canonical: "Greco", aliases: ["Greco"] },
  { canonical: "Cortese", aliases: ["Cortese"] },
  { canonical: "Arneis", aliases: ["Arneis"] },
  { canonical: "Verdicchio", aliases: ["Verdicchio"] },
  { canonical: "Assyrtiko", aliases: ["Assyrtiko"] },
  { canonical: "Furmint", aliases: ["Furmint"] },
  { canonical: "Grillo", aliases: ["Grillo"] },
  { canonical: "Catarratto", aliases: ["Catarratto"] },
  { canonical: "Picpoul", aliases: ["Picpoul", "Piquepoul"] },
  { canonical: "Marsanne", aliases: ["Marsanne"] },
  { canonical: "Roussanne", aliases: ["Roussanne"] },
  { canonical: "Sylvaner", aliases: ["Sylvaner", "Silvaner"] },
  { canonical: "Müller-Thurgau", aliases: ["Müller-Thurgau", "Muller-Thurgau", "Muller Thurgau"] },
  { canonical: "Kerner", aliases: ["Kerner"] },
  { canonical: "Scheurebe", aliases: ["Scheurebe"] },
  { canonical: "Colombard", aliases: ["Colombard"] },
  { canonical: "Folle Blanche", aliases: ["Folle Blanche"] },
  { canonical: "Melon de Bourgogne", aliases: ["Melon de Bourgogne", "Muscadet"] },
  { canonical: "Sercial", aliases: ["Sercial"] },
  { canonical: "Verdelho", aliases: ["Verdelho"] },
  { canonical: "Godello", aliases: ["Godello"] },
  { canonical: "Loureiro", aliases: ["Loureiro"] },
  { canonical: "Airén", aliases: ["Airén", "Airen"] },
  { canonical: "Xarel-lo", aliases: ["Xarel-lo", "Xarello"] },
  { canonical: "Parellada", aliases: ["Parellada"] },
  { canonical: "Palomino", aliases: ["Palomino"] },
  { canonical: "Pedro Ximénez", aliases: ["Pedro Ximénez", "Pedro Ximenez", "PX"] },
  { canonical: "Petit Manseng", aliases: ["Petit Manseng"] },
  { canonical: "Gros Manseng", aliases: ["Gros Manseng"] },
  { canonical: "Savagnin", aliases: ["Savagnin"] },
  { canonical: "Sauvignon Gris", aliases: ["Sauvignon Gris"] },
  { canonical: "Muscat of Alexandria", aliases: ["Muscat of Alexandria", "Moscatel de Alejandría", "Moscatel de Alejandria"] },

  // --- More reds, less common but still well-documented ---
  { canonical: "Marzemino", aliases: ["Marzemino"] },
  { canonical: "Refosco", aliases: ["Refosco"] },
  { canonical: "Vranac", aliases: ["Vranac"] },
  { canonical: "Plavac Mali", aliases: ["Plavac Mali"] },
  { canonical: "Sagrantino", aliases: ["Sagrantino"] },
  { canonical: "Négrette", aliases: ["Négrette", "Negrette"] },
  { canonical: "Fer Servadou", aliases: ["Fer Servadou", "Braucol", "Mansois"] },
  { canonical: "Norton", aliases: ["Norton"] },
  { canonical: "Concord", aliases: ["Concord"] },
  { canonical: "Chambourcin", aliases: ["Chambourcin"] },

  // --- More whites, less common but still well-documented ---
  { canonical: "Ribolla Gialla", aliases: ["Ribolla Gialla"] },
  { canonical: "Friulano", aliases: ["Friulano", "Sauvignonasse", "Sauvignon Vert"] },
  { canonical: "Glera", aliases: ["Glera", "Prosecco"] },
  { canonical: "Muscadelle", aliases: ["Muscadelle"] },
  { canonical: "Vidal Blanc", aliases: ["Vidal Blanc", "Vidal"] },
  { canonical: "Seyval Blanc", aliases: ["Seyval Blanc"] },
  { canonical: "Arinto", aliases: ["Arinto"] },
  { canonical: "Encruzado", aliases: ["Encruzado"] },
  { canonical: "Fernão Pires", aliases: ["Fernão Pires", "Fernao Pires", "Maria Gomes"] },
  { canonical: "Hárslevelű", aliases: ["Hárslevelű", "Harslevelu"] },
  { canonical: "Moschofilero", aliases: ["Moschofilero"] },
  { canonical: "Malagousia", aliases: ["Malagousia"] },
  { canonical: "Rkatsiteli", aliases: ["Rkatsiteli"] },
];
